# Generated by Django 6.0 on 2025-12-17 00:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('financial_account_id', models.AutoField(primary_key=True, serialize=False)),
                ('financial_account_name', models.CharField(max_length=75)),
                ('financial_account_type', models.CharField(choices=[('SAVINGS', 'Savings'), ('CREDIT_CARD', 'Credit card'), ('CURRENT', 'Current'), ('INVESTMENTS', 'Investments'), ('PENSION_PLAN', 'Pension plan')], default='CURRENT', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('transaction_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_impacted', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='backend_app.financialaccount')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='backend_app.subcategory')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='backend_app.transactiontype')),
            ],
        ),
        migrations.AddField(
            model_name='subcategory',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='backend_app.transactiontype'),
        ),
    ]
